### ISSUE TITLE
BUG: automatic change of  Numbering Format after second execution

### ISSUE THREAD

**Issue by EleacastBim** [ENGworks-DEV/RenumberParts#1]
**Describe the bug**
The numbering format is lost from the second element.
example:
First element: 001
Second element: 02

**Expected behavior**
The numbering format must be maintained, example: 001, 002,.....010, etc.

**Screenshots**

**Desktop (please complete the following information):**
 Revit versión 2019 - 19.1.0.112

**Comment by ENGworks-DEV** [comment]
Fixed in c3f207dd
