### ISSUE TITLE
BUG: Numbering adds only 1 leading zero after reopening the window

### ISSUE THREAD

**Issue by ENGworks-DEV** [ENGworks-DEV/RenumberParts#2]
**Describe the bug**
Settings save the integer number of the numbering and adds only one leading zero no matter how many char form the number. This ocurrs when reopening the window of RenumberParts

**To Reproduce**
1. Open renumber parts window
2. Fill prefix, separator and number with at least 2 leading zeros e.g. 003
3. Apply the number to one element 
4. Close the main window
5. Open the window again and now the number is 04 

**Expected behavior**
Number should be using the same amount of char/leading zeros as at the first run. ie 004

**Additional context**
Problem related with issue #1

**Comment by EleacastBim** [comment]
Issue Fixed
