### ISSUE TITLE
BUG: Shared Parameter is not available for tagging

### ISSUE THREAD

**Issue by EleacastBim** [ENGworks-DEV/RenumberParts#6]
**Describe the bug**
Shared Parameter "Item Number" is not available for tagging. 

**To Reproduce**
1. Lists a Duct whit the add-In
2. Try Tag the duct
3. Edit the Family Tag
4. Edit label
5. Search for the parameter in the list

**Expected behavior**
shared parameter Item Number field should appear in the Edit Label list for tagging

**Desktop (please complete the following information):**
 - Revit 2019

**Comment by ENGworks-DEV** [comment]
Not a bug, go to main project -> project parameters -> select "Item Number" -> Export . 
In the tag family -> label -> new parameter and select "Item Number" from the shared parameter file.
See...

https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/Revit-Model/files/GUID-AD648C07-0C2F-478D-AD9D-4F9A5FF515E6-htm.html
